#!/bin/bash

# File containing instance IDs
INSTANCE_FILE="instance_ids.txt"

# Prompt the user for confirmation
read -p "Are you sure you want to execute this script and stop instances? (yes/no): " CONFIRMATION

if [[ "$CONFIRMATION" != "yes" ]]; then
  echo "Script execution cancelled."
  exit 1
fi

# Check if the file exists
if [ ! -f "$INSTANCE_FILE" ]; then
  echo "File $INSTANCE_FILE does not exist."
  exit 1
fi

# Read the file line by line
while IFS= read -r INSTANCE_ID
do
  if [ -n "$INSTANCE_ID" ]; then
    # Get the current state of the instance
    INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" --query "Reservations[].Instances[].State.Name" --output text)

    if [ "$INSTANCE_STATE" == "running" ]; then
      # Stop the EC2 instance if it is running
      aws ec2 stop-instances --instance-ids "$INSTANCE_ID"

      # Check if the command was successful
      if [ $? -eq 0 ]; then
        echo "Successfully stopped instance: $INSTANCE_ID"
      else
        echo "Failed to stop instance: $INSTANCE_ID"
      fi
    else
      echo "Instance $INSTANCE_ID is not in running state (current state: $INSTANCE_STATE). Skipping."
    fi
  fi
done < "$INSTANCE_FILE"

sleep 120

# Display status of all servers after stopping instances
echo "Status of all servers after stopping instances:"
bash -x status.sh
